version: '3.7'

services:
  app:
    image: loadimpact/k6:0.33.0
    entrypoint: k6 run script.js
    cap_add:
      - NET_RAW
    cap_drop:
      - ALL
    privileged: false
    volumes:
      - ./src:/home/k6:ro
      - ./config.json:/home/k6/.config/loadimpact/k6/config.json:ro
    networks:
      - local_net

networks:
  local_net:

